### ISSUE TITLE
Bug in double letter words

### ISSUE THREAD

**Issue by sweenu** [nimblebun/wordle-cli#1]
![screenshot_2022-02-13-213239](https://user-images.githubusercontent.com/7051978/153773850-5a85a3c0-d5ba-403f-a51e-39dfc3b45586.png)

As you can see in the above picture, there is a bug on the fourth try, the second N should be gray.

**Comment by jozsefsallai** [comment]
Hey!

Thanks for reporting this bug to us! This is actually the same mistake @3b1b talked about in [his video](https://www.youtube.com/watch?v=fRed0Xmc2Wg) - it's a very easy thing to miss. But the good news is that it's already being worked on (amongst other smaller bugs and improvements)! Next release should be out in the coming days.

**Comment by sweenu** [comment]
Yes! I wouldn't have known it was a bug and not an expected rule of the game had I not watched the video.
Good work on this cli version, I really like it :)
