### ISSUE TITLE
Shows You lost but word is correct

### ISSUE THREAD

**Issue by Krypion17** [nimblebun/wordle-cli#14]
![image](https://user-images.githubusercontent.com/74854681/163528664-e424f0a5-c975-488c-a3de-0dea0ae1d319.png)

**Comment by Krypion17** [comment]
![image](https://user-images.githubusercontent.com/74854681/163925527-ad043510-e537-4268-8efd-95a276f7b124.png)
Seems to happen only on the last guess.

**Comment by jozsefsallai** [comment]
Sorry for the late notice but this has been fixed in the latest release!
