### ISSUE TITLE
Carriage return (ENTER) not working

### ISSUE THREAD

**Issue by xxxserxxx** [nimblebun/wordle-cli#3]
The carriage return key doesn't work on the starting word -- but only some words -- in v1.0.2.  Type all 5 characters, hit ENTER, and nothing happens. For example, STEAM, SMART, and TRIED do not work, but SOARS and MEATS do.  Downgraded to v1.0.1, and it all (valid) words work.

Version: v1.0.2   
Go: go1.17.7 linux/amd64   
Shell: st + tmux

**Comment by sweenu** [comment]
@jozsefsallai The `ValidWordList` does not include the list of possible guesses (`WordList`). That is why enter does not work in v1.0.2 for most common words.

**Comment by jozsefsallai** [comment]
Thank you for the bug report! This has been fixed in v1.0.3 - it can be downloaded from the releases page or the apt repository. Apologies for the big oversight :)
